# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

# USE ROM_ROBOT_MODEL as ( bobo | yoyo | rom2109 ) in BASHRC

startup_window: Hardware
# startup_pane: 0

windows:
  - Hardware: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_controller hardware.launch.py odom_tf:=False use_rviz:=False use_lidar:=True use_imu:=True
  - EKF: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_ekf ekf.launch.py publish_tf:=True use_sim_time:=False
  - CartoSwitcherQt: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3;ros2 run which_maps which_maps_server
  - NavSwitcherQt: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 run which_maps which_nav_server #ros2 launch ${ROM_ROBOT_MODEL}_nav2 hw_navigation.launch.py use_composition:=False use_sime_time:=False
  - Flutter: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/Desktop/Git/rom_dynamics_robots/submodule_packages/ros_flutter_gui_app_web; python3 -m http.server 8000
  - RosBridgeServer: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rosbridge_server rosbridge_websocket_launch.xml
  - Debug: 
      root: ~/
      panes:
        - clear; source ~/.bashrc;
