# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

# USE ROM_ROBOT_MODEL as ( bobo | yoyo | rom2109 ) in BASHRC

startup_window: Hardware
# startup_pane: 0

windows:
  - Hardware: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_controller hardware.launch.py odom_tf:=False use_rviz:=False use_lidar:=True use_imu:=True
  - EKF: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_ekf ekf.launch.py publish_tf:=True use_sim_time:=False
  - Navigation: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; ros2 launch ${ROM_ROBOT_MODEL}_nav2 mapping.launch.py map_subscribe_transient_local:=true use_slamtoolbox:=False
  - JoyStick: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom_robotics_joy joystick.launch.py
  - Debug: 
      root: ~/
      panes:
        - clear; source ~/.bashrc;
