twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_collision_to_twist # rviz goal
        timeout: 0.5
        priority: 10
      behavior:
        topic: cmd_vel_bt_to_twist # behavior tree or server ?
        timeout: 0.5
        priority: 100
      joystick:
        topic: cmd_vel_joy_to_twist # behavior tree
        timeout: 0.5
        priority: 100
      web:
        topic: /turtle1/cmd_vel # behavior tree
        timeout: 0.5
        priority: 100
