# ./.tmuxinator.yml

name: ROM Dynamics 
root: /mytmux/bags

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: TwistKeyboard
# startup_pane: 0

windows:
  - Hardware: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_controller hardware.launch.py odom_tf:=False use_rviz:=False use_lidar:=True use_imu:=True
  - EKF: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch ${ROM_ROBOT_MODEL}_ekf ekf.launch.py publish_tf:=True use_sim_time:=False
  - Navigation: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 3; #ros2 launch ${ROM_ROBOT_MODEL}_nav2 mapping.launch.py map_subscribe_transient_local:=true use_slamtoolbox:=False
  - JoyStick: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rom_robotics_joy joystick.launch.py
  - ROSBag: 
      root: /mytmux/bags
      panes:
        - clear; source ~/.bashrc; sleep 10; ros2 bag record -o office_data_$(rom_date) /clock /scan /tf /tf_static /imu/out /odom 
  - Npm: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; cd /home/mr_robot/devel_ws/src/rom2109/funviz-main; npm start
  - RosBridgeServer: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch rosbridge_server rosbridge_websocket_launch.xml port:=7070
  - Debug: 
      root: ~/
      panes:
        - clear; source ~/.bashrc;




