# ./.tmuxinator.yml

name: ROM Dynamics 
root: /mytmux/bags

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: TwistKeyboard
# startup_pane: 0

windows:
  - Gazebo: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch romrobots_gazebo simulation.launch.py use_rviz:=True odom_tf:=False
  - EKF: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch bobo_ekf ekf.launch.py publish_tf:=True use_sim_time:=False
  - TwistKeyboard: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap /cmd_vel:=/cmd_vel_keyboard 
  - ROSBag: 
      root: /mytmux/bags
      panes:
        - clear; source ~/.bashrc; sleep 10; ros2 bag record -o five_rooms_v0.5_w0.3_data /clock /scan /tf /tf_static /imu/out /odom 
  - RQtPublisher: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; sleep 10; ros2 run rqt_publisher rqt_publisher 




