/smoother_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    robot_base_frame: base_link
    simple_smoother:
      do_refinement: true
      max_its: 1000
      plugin: nav2_smoother::SimpleSmoother
      tolerance: 1.0e-10
      w_data: 0.2
      w_smooth: 0.3
    smoother_plugins:
    - simple_smoother
    transform_tolerance: 0.1
    use_sim_time: false

